export const FETCH_SUMMARY = "FETCH_SUMMARY";
export const FETCH_SUMMARY_FAILED = "FETCH_SUMMARY_FAILED";
export const FETCH_SUMMARY_SUCCESS = "FETCH_SUMMARY_SUCCESS";

export const FETCH_COUNTRY = "FETCH_COUNTRY";
export const FETCH_COUNTRY_SUCCESS = "FETCH_COUNTRY_SUCCESS";
export const FETCH_COUNTRY_FAILED = "FETCH_COUNTRY_FAILED";